CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(45) NOT NULL,
  password VARCHAR(255) NOT NULL,
  UNIQUE (username),
  UNIQUE (id)
);

CREATE TABLE worlds (
  id SERIAL PRIMARY KEY,
  ownerId SERIAL NOT NULL,
  name VARCHAR(45) NOT NULL,
  password VARCHAR(45),
  UNIQUE (id),
  CONSTRAINT ownerId FOREIGN KEY (ownerId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE worldUsers (
  id SERIAL PRIMARY KEY,
  userId SERIAL NOT NULL,
  worldId SERIAL NOT NULL,
  avatarChoice VARCHAR(45) NOT NULL,
  UNIQUE (id),
  CONSTRAINT userId FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT worldId FOREIGN KEY (worldId) REFERENCES worlds(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE worldMessages (
  id SERIAL PRIMARY KEY,
  text VARCHAR(250) NOT NULL,
  authorId SERIAL NOT NULL,
  worldId SERIAL NOT NULL,
  created_at DATE NOT NULL,
  UNIQUE (id),
  CONSTRAINT authorId FOREIGN KEY (authorId) REFERENCES worldUsers(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT messageWorldId FOREIGN KEY (worldId) REFERENCES worlds(id) ON DELETE CASCADE ON UPDATE CASCADE
);